baseurl: "/leesonderzoek"

paginate: 10
paginate_path: "/blog/page:num/"

permalink: /:categories/:title/

plugins:
  [jekyll-paginate]

collections     :
  publicaties   :
    output      : true
    permalink   : /:collection/:path
